Product Management Assignment/ProductManagement/ProductManagement/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProductManagement.Models;
using System.Web.Security;
namespace ProductManagement.Controllers
{
    // For Authentication
    public class AuthController : Controller
    {
        GatewayEntities db = new GatewayEntities();

        //For Login Get Method
        // GET: Auth
        public ActionResult Login()
        {
            return View();
        }


        // For Login POST Method
        [HttpPost]
        public ActionResult Login(User user)
        {
            if (ModelState.IsValid)
            {
                //Checking if User is Authenticated or Not

                var auth = db.Users.Where(a => a.Email.Equals(user.Email) && a.Password.Equals(user.Password)).FirstOrDefault();
                if (!(auth == null))
                {
                    //Setting Authentication Cookies and Session

                    FormsAuthentication.SetAuthCookie(user.Email, false);
                    Session["User_Id"] = auth.User_Id;
                    Session["Username"] = auth.Username;
                    return RedirectToAction("Index", "Home");

                }
            }
            ModelState.AddModelError("", "You Entered Wrong Credentials");
            return View();
        }

        //For Registration Of User
        public ActionResult Signup()
        {
            return View();
        }

        //POST Method For Registration
        [HttpPost]
        public ActionResult Signup(User user)
        {
            if (ModelState.IsValid)
            {
                //Adding User To the Database
                var auth = db.Users.Add(user);
                db.SaveChanges();

                //Setting Authentication Cookies and Session
                FormsAuthentication.SetAuthCookie(user.Username, false);
                Session["User_Id"] = auth.User_Id;
                Session["Username"] = auth.Username;

                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "You Entered Wrong Credentials");
            return View();
        }

        // For Signout Of User
        public ActionResult Signout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Product Management Assignment/ProductManagement/ProductManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/default.min.css" rel="stylesheet" />

    <link href="~/Content/sweetalert/sweet-alert.css" rel="stylesheet" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-light navbar-fixed-top bg-light" style="background-color: #e3f2fd;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        <li class="nav-item navbar-btn ">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="nav-item navbar-btn ">@Html.ActionLink("Products List", "Index", "Product")</li>
                        
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="nav-item navbar-btn"><button class="btn btn-success"><a href="@Url.Action("Signout","Auth")" style="color: white;text-decoration: none"> Signout </a></button></li>

                    </ul>
                }


            </div>
        </div>
    </div>
 
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
<script src="~/Scripts/alertify.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.css" integrity="sha512-hwwdtOTYkQwW2sedIsbuP1h0mWeJe/hFOfsvNKpRB3CkRxq8EW7QMheec1Sgd8prYxGm1OM9OZcGW7/GUud5Fw==" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.js" integrity="sha512-XVz1P4Cymt04puwm5OITPm5gylyyj5vkahvf64T8xlt/ybeTpz4oHqJVIeDtDoF5kSrXMOUmdYewE4JS/4RWAA==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.css" integrity="sha512-f8gN/IhfI+0E9Fc/LKtjVq4ywfhYAVeMGKsECzDUHcFJ5teVwvKTqizm+5a84FINhfrgdvjX8hEJbem2io1iTA==" crossorigin="anonymous" />
<script src="https://lipis.github.io/bootstrap-sweetalert/lib/sweet-alert.js">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-sweetalert/1.0.1/sweetalert.min.js" integrity="sha512-MqEDqB7me8klOYxXXQlB4LaNf9V9S0+sG1i8LtPOYmHqICuEZ9ZLbyV3qIfADg2UJcLyCm4fawNiFvnYbcBJ1w==" crossorigin="anonymous"></script>